sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js: 6
branches:
  only:
    - master
notifications:
  email: false
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
script:
  - npm run validate
